theme: osuny-www-design-system
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  plausible: support.osuny.org
  pages:
    default_image: true
  search:
    active: true
    positions:
      - footer