theme: osuny-www-design-system
_merge: deep
params:
  plausible: support.osuny.org
  menu:
    primary:
      level_1:
        dropdown: true
      level_2:
        title:
          active: true
  search:
    active: true
    positions:
      - primary
      - footer
